# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8998
  servlet:
    context-path: /

# 系统自定义全局配置，可根据实际需要扩展使用
global:
  upload-location: /Users/malailaowang/IdeaProjects/springboot-template-master/upload/ #文件上传目录
  upload-mapping: /Users/malailaowang/IdeaProjects/springboot-template-master/upload #文件上传目录访问路径
  redis-session-dao: true #是否使用使用redis会话管理器，true为开启，false为关闭
  kaptcha-enable: false #是否开启验证码，true为开启，false为关闭

# jwt配置
jwt:
  secret: 1235ggguu888ds  #jwt密钥
  expiration: 604800  #过期时间,秒

spring:
  # 环境 sit:集成测试环境|pre:预生产环境|prd:生成环境
  profiles:
    active: local
  mvc:
    static-path-pattern: /static/**
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# Mybatis配置
mybatis:
  configLocation: classpath:mybatis.xml
  mapper-locations: classpath*:net/chenlin/dp/**/mapper/*.xml

aliyun:
  oss:
    endpoint: hit-on.oss-cn-hongkong.aliyuncs.com
    appPoint: oss-cn-hongkong.aliyuncs.com
    accessKeyId: LTAI5t7mJ7X6HfMCrxmr4GKt
    accessKeySecret: qpmAZ9rsmgbxvMKXSelmNq8sWhpTCZ
    bucketname: hit-on

log:
  level:
    root: info
  file: ./logs/springboot-mybatis.log
  maxsize: 10MB

telegram:
  robotToken: 5509412236:AAEVKk13si4gxudv7KA79JFXtiyuByhaXjk
  groupId: -1001718074576